spring:
  profiles:
    active: dev
    include: postgresql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:18080/auth
  realm: tasks
  resource: task-client
  credentials:
    secret: 0921c31d-609e-44c4-8192-51b84cf3fa53
  bearer-only: true
  public-client: true
  security-constraints:
    - auth-roles:
        - task-role
      security-collections:
        - name:
          patterns:
            - /api/*

logging:
  level:
    org.keycloak: TRACE