spring:
  profiles:
    active: dev
    include: postgresql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:18080/auth
  realm: tasks
  resource: task-client
  credentials:
    secret: ef3f048c-70a8-4db5-807b-cfdab41d9a7d
  bearer-only: true
  public-client: true
  security-constraints:
    - auth-roles:
        - task-role
      security-collections:
        - name:
          patterns:
            - /api/tasks/*

logging:
  level:
    org.keycloak: TRACE