spring:
  profiles:
    active: local

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://postgresql:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: tasks
  resource: task-client
  credentials:
    secret: ef3f048c-70a8-4db5-807b-cfdab41d9a7d
  bearer-only: true
  public-client: true
  security-constraints:
    - auth-roles:
        - task-role
      security-collections:
        - name:
          patterns:
            - /api/tasks/*

server:
  port: 9090

logging:
  level:
    org.keycloak: TRACE