version: '2'

services:
  # Backend
  tasks-spring-service:
    container_name: tasks-spring-service
    build:
      context: ./tasks-spring-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "5006:5006"
      - "6565:6565"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"


  # Frontend
  tasks-react-app:
    container_name: tasks-react-app
    build:
      context: ./tasks-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

#  python-service:
#    build:
#      context: ./python-service
#      dockerfile: Dockerfile
#    ports:
#      - "18081:8080"
#      - "5007:5007"

  postgresql:
    container_name: tasks-postgresql
    image: "postgres"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"

  # I always forget how to set up the damn keycloak configs (creating client, role, user...)
  # so, look here to refresh memory:
  # Create Role / Create User / Add Role to User / Create Client (confidential with OAuth enabled) / Service Account Role
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    volumes:
      - ./keycloak:/keycloak
    ports:
      - "8080:8080"
      - "5007:5007"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
    hostname: keycloak