### Request admin token
POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admin-cli&username=admin&password=admin


### Create realm ... work in progress
POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlclloeks0N05RdEllWmF6ZkxDelhrUGpuZGpYQmp2T2ZWTXNrQ1ZfcTlNIn0.eyJleHAiOjE2MDg2NDU0ODUsImlhdCI6MTYwODY0NTQyNSwianRpIjoiOTM4NmRhZjAtNzRhOC00OTU5LWExNzctNTIzOGJlOWU1MzJhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL21hc3RlciIsInN1YiI6IjM0YjVlZTM5LTRjNzItNDVlNi1iYzdkLTViYTM5OTkxM2ZlOSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiI0MWY1NWRlOS1hYWY3LTQ5NGEtOWExYS0xZTU5Mzc2MGQxZWUiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiJ9.ezbbJYvZvAn8ZasA6aNtHWcrH5lDAD-z7Xxpl7SW-LvBPaOhGfJ-lZ7EsxWL91ECmdn9cfQVHgnJUbSU_eaiGArvd8EW4V6-vLbxI4YthA7tdykXyX-Hq4JwWpKVgr4kLjrDzfU108rh69Py6shPM7-eMMFmYViCa4hm9SwlR-Bvs280MTO9tWKd2_mJGcCrsCzyQOXo1hrUn1HgtUh4YEBFDswqJZa5nAmNKu3AGU4s5FnkvSpOlYr3EBiGgrFnZHLakyVHAP_kE1iJMde0zChtPXtiKpHp6WrUMSNAtZPb1Imykw0rAv5zt9k35UPUDuXeN5r0FSYkN4wTuflwdw

{
  "id": "tasks",
  "realm": "tasks"
}