### Request admin token
POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admin-cli&username=admin&password=admin


### Create realm ... work in progress
POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlclloeks0N05RdEllWmF6ZkxDelhrUGpuZGpYQmp2T2ZWTXNrQ1ZfcTlNIn0.eyJleHAiOjE2MTE0OTI0NTEsImlhdCI6MTYxMTQ5MjM5MSwianRpIjoiZGIwMDI2NDAtOTg4NS00NmZhLWExNGYtNzZkYmJiZmU3ZThmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL21hc3RlciIsInN1YiI6IjM0YjVlZTM5LTRjNzItNDVlNi1iYzdkLTViYTM5OTkxM2ZlOSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJlZjAwMGNhNi04ZWUzLTQ5MGYtYmM0NS04M2U4MjA2YmI1ZDEiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiJ9.GEhmwc4ZcWB1mqgdDTl6SKWhpBVtS6zh7ScBjdDOxTR_iMhhehiR1WmtvbarS5qcvd3eTmnfJ-aVBNKGZmk8Ywzj7qhIgG_iDuZSAShply8qGCgdW3eVMPfO7sXPBOLwlFytaNey6ZIkwcfJeP22fSgy7AslBuAXNiWIueQ6sbUt-jXCEitdfUbSr5IDSK3L5ZQU5zB6oZID3g4zVOw0qnT2PMM-fhDOOD2lvhL4pyzS80r6a2racdY7mYw4tDXQWZ7TDqm94bvoRAgC1dY-xAOe3AdFxpv5_GCwysS3sEDCFG2uRcJbkRHQ0CD1eTq5iNLt_CJMMpZa4G3wmvzHiw

{
  "id": "tasks",
  "realm": "tasks"
}